### ISSUE TITLE
--eval crashes with lambdas

### ISSUE THREAD

**Issue by samuelgruetter** [epfl-lara/leon#110]
Verification accepts the following program:

```
import leon.lang._

object Test {
  val foo = (x: BigInt) => x
  
  def lemma1(x: BigInt) = {
    foo(x) == x
  }.holds
}
```

But with `--eval`, I get an error:

```
[  Info  ]  - Evaluating foo
leon.codegen.CompilationException: Unsupported return value : class Leon$CodeGen$Lambda$5 while expecting (BigInt) => BigInt
	at leon.codegen.CompilationUnit.jvmToExpr(CompilationUnit.scala:247)
	at leon.codegen.CompiledExpression.evalFromJVM(CompiledExpression.scala:48)
	at leon.codegen.CompiledExpression.eval(CompiledExpression.scala:58)
	at leon.evaluators.CodeGenEvaluator$$anonfun$compile$1.apply(CodeGenEvaluator.scala:43)
	at leon.evaluators.CodeGenEvaluator$$anonfun$compile$1.apply(CodeGenEvaluator.scala:41)
	at leon.evaluators.CodeGenEvaluator$$anonfun$eval$2.apply(CodeGenEvaluator.scala:27)
	at leon.evaluators.CodeGenEvaluator$$anonfun$eval$2.apply(CodeGenEvaluator.scala:24)
	at scala.Option.map(Option.scala:146)
	at leon.evaluators.CodeGenEvaluator.eval(CodeGenEvaluator.scala:24)
	at leon.evaluators.Evaluator.eval(Evaluator.scala:18)
	at leon.evaluators.EvaluationPhase$$anonfun$run$1.apply(EvaluationPhase.scala:36)
	at leon.evaluators.EvaluationPhase$$anonfun$run$1.apply(EvaluationPhase.scala:33)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at leon.evaluators.EvaluationPhase$.run(EvaluationPhase.scala:33)
	at leon.evaluators.EvaluationPhase$.run(EvaluationPhase.scala:10)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:12)
	at leon.Main$.execute(Main.scala:248)
	at leon.Main$.main(Main.scala:232)
	at leon.Main.main(Main.scala)
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/leon/pull/111
