### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by BLepers** [epfl-lara/leon#223]
The following file results in a java.util.NoSuchElementException:

```scala
import leon.collection._
import leon.lang._
import scala.Any
import leon.annotation._
import leon.proof._
import leon.instrumentation._
import leon.invariant._
import leon.util.Random

object Test {
   val seed:Random.State = Random.State(0);
   val t:T = T(Random.nextBigInt(seed));

   case class T(n:BigInt) {
      require(n >= 0);
   }
}
```

```
$ leon test.scala 
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at leon.xlang.AntiAliasingPhase$$anonfun$24.apply(AntiAliasingPhase.scala:271)
	at leon.xlang.AntiAliasingPhase$$anonfun$24.apply(AntiAliasingPhase.scala:269)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at leon.xlang.AntiAliasingPhase$.leon$xlang$AntiAliasingPhase$$mapApplication$1(AntiAliasingPhase.scala:269)
	at leon.xlang.AntiAliasingPhase$$anonfun$leon$xlang$AntiAliasingPhase$$makeSideEffectsExplicit$1.apply(AntiAliasingPhase.scala:410)
	at leon.xlang.AntiAliasingPhase$$anonfun$leon$xlang$AntiAliasingPhase$$makeSideEffectsExplicit$1.apply(AntiAliasingPhase.scala:300)
	at leon.purescala.GenTreeOps$class.rec$2(GenTreeOps.scala:329)
	at leon.purescala.GenTreeOps$$anonfun$15.apply(GenTreeOps.scala:335)
	at leon.purescala.GenTreeOps$$anonfun$15.apply(GenTreeOps.scala:335)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at leon.purescala.GenTreeOps$class.rec$2(GenTreeOps.scala:335)
	at leon.purescala.GenTreeOps$class.preMapWithContext(GenTreeOps.scala:345)
	at leon.purescala.ExprOps$.preMapWithContext(ExprOps.scala:35)
	at leon.xlang.AntiAliasingPhase$.leon$xlang$AntiAliasingPhase$$makeSideEffectsExplicit(AntiAliasingPhase.scala:475)
	at leon.xlang.AntiAliasingPhase$$anonfun$13.apply(AntiAliasingPhase.scala:203)
	at leon.xlang.AntiAliasingPhase$$anonfun$13.apply(AntiAliasingPhase.scala:202)
	at scala.Option.map(Option.scala:146)
	at leon.xlang.AntiAliasingPhase$.leon$xlang$AntiAliasingPhase$$updateBody(AntiAliasingPhase.scala:202)
	at leon.xlang.AntiAliasingPhase$$anonfun$apply$3.apply(AntiAliasingPhase.scala:93)
	at leon.xlang.AntiAliasingPhase$$anonfun$apply$3.apply(AntiAliasingPhase.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at leon.xlang.AntiAliasingPhase$.apply(AntiAliasingPhase.scala:91)
	at leon.TransformationPhase.run(LeonPhase.scala:22)
	at leon.TransformationPhase.run(LeonPhase.scala:17)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:12)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:10)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:10)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:10)
	at leon.xlang.XLangDesugaringPhase$.run(XLangDesugaringPhase.scala:28)
	at leon.xlang.XLangDesugaringPhase$.run(XLangDesugaringPhase.scala:9)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:10)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:12)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:10)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:10)
	at leon.utils.PreprocessingPhase.run(PreprocessingPhase.scala:48)
	at leon.utils.PreprocessingPhase.run(PreprocessingPhase.scala:12)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:12)
	at leon.Pipeline$$anon$1.run(Pipeline.scala:10)
	at leon.Main$.execute(Main.scala:267)
	at leon.Main$.main(Main.scala:251)
	at leon.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

Thanks,

**Comment by regb** [comment]
Unfortunately, we currently don't support stateful object (Random.State) in global variables (the val is visible in all functions). I will try to detect it to have a proper error message, but if you want to use mutable objects you need to pass them around from functions to functions, or case classes.

**Comment by regb** [comment]
The error should now be clearer in d438a39485db86fa20e3ca9821e671b113d6b6b7
