### ISSUE TITLE
leon with isabelle, undefined session, documentation

### ISSUE THREAD

**Issue by tomjridge** [epfl-lara/leon#237]
Dear All,

I am trying to use leon to generate Isabelle thy files from some scala source. Compilation is fine. I can run leon using cvc4 on Addresses.scala and it seems to work. Now I want to run Isabelle.

* There doesn't seem to be much documentation on how to do this

I try the following, and get an error:

```
tr61@pc1177:/tmp/l/git/github/other/leon$ ./leon --solvers=isabelle testcases/verification/Addresses.scala 
./leon --solvers=isabelle testcases/verification/Addresses.scala 
[Warning ] warning: there were two feature warnings; re-run with -feature for details
[  Info  ] Preparing Isabelle setup (this might take a while) ...
[  Info  ] Building session ...
ERROR(Undefined session(s): "Leon")
	at isabelle.Library$ERROR$.apply(library.scala:33)
	at isabelle.Library$.error(library.scala:37)
	at isabelle.Basic_Library$$anonfun$2.apply(library.scala:223)
	at isabelle.Basic_Library$$anonfun$2.apply(library.scala:223)
	at isabelle.Build$Session_Tree.selection(build.scala:149)
	at isabelle.Build$.build_results(build.scala:758)
	at isabelle.Build$.build(build.scala:1001)
	at edu.tum.cs.isabelle.impl.Environment.build(Environment.scala:46)
	at edu.tum.cs.isabelle.System$.build(System.scala:38)
	at leon.solvers.isabelle.IsabelleEnvironment$$anonfun$4$$anonfun$apply$1.apply(IsabelleEnvironment.scala:69)
	at leon.solvers.isabelle.IsabelleEnvironment$$anonfun$4$$anonfun$apply$1.apply(IsabelleEnvironment.scala:67)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

* What am I doing wrong?

**Comment by larsrh** [comment]
Weird, I thought I fixed this problem in #189. In order to debug this, could you please answer the following:

* What Leon version (i.e. which commit hash) are you running? Something recent?
* Have you run `sbt package` and `sbt script` recently before running `./leon`?
* Can you try running `./leon` again with `--debug=isabelle` and paste the log output here?

Some more documentation is [available](http://leon.epfl.ch/doc/isabelle.html). Anything you found missing there?

**Comment by tomjridge** [comment]
I'm on master:

```
git log |head
commit 414657252a27f61ef3d9e43d3c4df6f1cd37408d
Author: Regis Blanc <regwblanc@gmail.com>
Date:   Fri Aug 5 15:24:31 2016 +0200

    no recursion into lets
```

I ran `sbt script` , not `sbt package`. After `sbt package; sbt script` things appear to work ("Building session"). 

Thanks!

**Comment by tomjridge** [comment]
For the documentation, I think a run through of command line leon usage, for working with isabelle (for various use cases), would help. 

Looking forward to verifying my scala code! Great work all.

**Comment by larsrh** [comment]
Cool! Ticket can be closed now.
